apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":8080,"protocol":"TCP","serviceName":"fleet-single-cluster-demo:demoapp-loadbalancer","allNodes":false}]'
spec:
  selector:
    matchLabels:
      app: demoapp
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
        version: v1
    spec:
      containers:
      - name: demoapp
        image: demo.harbor.cnrancher.com/rancher/demoapp:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
