apiVersion: v1
kind: Service
metadata:
  name: demoapp-loadbalancer
  labels:
    app: demoapp
    version: v1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  labels:
    app: demoapp
    version: v1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demoapp
    version: v1
