apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:fleet-single-cluster-demo:demoapp"]'
  name: demoapp-loadbalancer
  labels:
    app: demoapp
    version: v1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:fleet-single-cluster-demo:demoapp"]'
  name: demoapp-loadbalancer
  labels:
    app: demoapp
    version: v1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
